(() => {
'use strict';
const WORLD = window.BELAVADOS_WORLD_DATA;
const ATLAS = window.BELAVADOS_CLICKABLE_GEOJSON;
const NAT = window.BELAVADOS_NATURAL_SYSTEMS;
if (!WORLD) throw new Error('assets/js/canonical_world_data.js did not load');
if (!ATLAS) throw new Error('assets/js/clickable_geojson_data.js did not load');
if (!NAT) throw new Error('assets/js/natural_systems_data.js did not load');
const MAP_W=WORLD.map.width, MAP_H=WORLD.map.height, ACTIVE_H=WORLD.map.activeSurfaceHeight;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v===null||v===undefined||v===''?'—':(typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:2}):String(v));
const arr=v=>Array.isArray(v)?v:(v?String(v).split(';').map(x=>x.trim()).filter(Boolean):[]);
const norm=v=>String(v??'').normalize('NFKC').replace(/[’‘`]/g,"'").trim().toLowerCase();
const chipList=v=>`<div class="chips">${arr(v).map(x=>`<span class="chip">${esc(x)}</span>`).join('')||'<span class="tiny">None recorded</span>'}</div>`;
const state={province:'',zoom:1,selected:null,labels:true};
const provinceByName=new Map(WORLD.provinces.map(p=>[norm(p.name),p]));
const settlementByName=new Map(WORLD.settlements.map(s=>[norm(s.name),s]));
const features=ATLAS.features;
if (!Array.isArray(features) || !features.length) throw new Error('Clickable GeoJSON contains no features');
const provinceBorders=features.filter(f=>f.properties.featureKind==='province-border');
const territoryBorders=features.filter(f=>f.properties.featureKind==='territory-border');
const centers=features.filter(f=>f.properties.featureKind==='province-center-pin');
const pins=features.filter(f=>['settlement-pin','territory-pin'].includes(f.properties.featureKind));
const naturalFeatures=NAT.features||[];
const routes=WORLD.routes||[];
function pinType(s){const t=String(s.settlementType||s.type||'village').toLowerCase();if(t.includes('capital'))return'capitalcity';if(t.includes('city'))return'city';if(t.includes('town'))return'town';return'village'}
function provinceKey(p){return p.iconKey||p.provinceKey||String(p.name).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9]+/g,'_').replace(/^_|_$/g,'').toLowerCase()}
function svg(tag,attrs={}){const el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);return el}
function polygonPath(coords){return coords.map(ring=>'M '+ring.map(pt=>pt.join(' ')).join(' L ')+' Z').join(' ')}
function drawGrid(){const layer=$('gridOverlay');layer.innerHTML='';for(let lon=-180;lon<=180;lon+=15){const x=(lon+180)/360*MAP_W;layer.append(svg('line',{x1:x,y1:0,x2:x,y2:ACTIVE_H,class:'grid-line'}));const tx=svg('text',{x:x+3,y:14,class:'grid-label'});tx.textContent=lon===0?'UTC±0':`UTC${Math.max(-12,Math.min(12,Math.floor((lon+7.5)/15)))>=0?'+':''}${Math.max(-12,Math.min(12,Math.floor((lon+7.5)/15)))}`;layer.append(tx)}for(let lat=-75;lat<=75;lat+=15){const y=(90-lat)/180*ACTIVE_H;layer.append(svg('line',{x1:0,y1:y,x2:MAP_W,y2:y,class:'grid-line'}))}}
function drawOverlays(){
 const layer=$('provinceOverlay');layer.innerHTML='';
 if(!state.province)return;
 const key=norm(state.province);
 if($('showBorders').checked){
  provinceBorders.filter(f=>norm(f.properties.province)===key).forEach(f=>{const p=f.properties;const path=svg('path',{d:polygonPath(f.geometry.coordinates),class:'province-border','data-name':p.province});path.style.setProperty('--border',p.borderColor||p.color||'#00ffff');path.style.setProperty('--width',`${p.borderWidth||8}px`);path.addEventListener('click',()=>showProvince(p.province));layer.append(path)});
  territoryBorders.filter(f=>norm(f.properties.province)===key).forEach(f=>{const p=f.properties;const path=svg('path',{d:polygonPath(f.geometry.coordinates),class:'territory-border'});path.style.setProperty('--border',p.borderColor||p.provinceColor||'#f4edb8');path.addEventListener('click',()=>showProvince(p.province));layer.append(path)});
 }
 if($('showCenters').checked){centers.filter(f=>norm(f.properties.province)===key).forEach(f=>{const p=f.properties,[x,y]=f.geometry.coordinates;const im=svg('image',{x:x-15,y:y-39.1667,width:30,height:39.1667,href:`assets/pins/provinces/${provinceKey(p)}.svg`,class:'province-center'});im.addEventListener('click',()=>showProvince(p.province));layer.append(im)})}
 if($('showRoutes')?.checked){routes.filter(r=>norm(r.province)===key).forEach(r=>{const pts=r.points||[];if(pts.length<2)return;const line=svg('polyline',{points:pts.map(p=>`${p.x},${p.y}`).join(' '),class:'placement-route'});line.setAttribute('data-modes',(r.modes||[]).join(', '));const title=svg('title');title.textContent=`${r.from} ↔ ${r.to} · ${(r.modes||[]).join(', ')}`;line.append(title);layer.append(line)})}
 if($('showNatural').checked)drawNatural(layer);
}
function drawNatural(layer){
 const key=norm(state.province);naturalFeatures.forEach((n,i)=>{const roots=[...(n.lore_roots||[]),n.naming_basis?.root_province,n.naming_basis?.root_name].filter(Boolean).map(norm);if(key&&!roots.includes(key))return;const a=n.coordinate_anchor;if(!Array.isArray(a)||a.length<2)return;const x=(Number(a[0])+180)/360*MAP_W,y=(90-Number(a[1]))/180*ACTIVE_H;const c=svg('circle',{cx:x,cy:y,r:3.2,class:'natural-dot'});c.addEventListener('click',()=>showNatural(n));layer.append(c)})
}
function drawPins(){const layer=$('pinLayer');layer.innerHTML='';if(!state.province||!$('showSettlements').checked)return;const key=norm(state.province);pins.filter(f=>norm(f.properties.province)===key).forEach(f=>{const s=settlementByName.get(norm(f.properties.settlement||f.properties.name))||f.properties;const [x,y]=f.geometry.coordinates;const b=document.createElement('button');b.className='map-pin'+(s.isTerritory?' territory':'');b.style.left=`${x}px`;b.style.top=`${y}px`;b.dataset.label=s.name+(($('showTimeZones').checked&&s.utc)?` · ${s.utc}`:'');b.title=`${s.name} — ${s.settlementType}`;const im=document.createElement('img');im.src=`assets/pins/settlements/${pinType(s)}.svg`;im.alt='';b.append(im);b.addEventListener('click',e=>{e.stopPropagation();showSettlement(s,b)});layer.append(b)})}
function apply(){state.zoom=Number($('mapZoom').value)||1;$('mapStage').style.width=`${MAP_W*state.zoom}px`;$('mapStage').style.height=`${MAP_H*state.zoom}px`;$('mapInner').style.transform=`scale(${state.zoom})`;document.documentElement.style.setProperty('--labels',$('showLabels').checked?'block':'none');$('gridOverlay').style.display=$('showGrid').checked?'block':'none';drawOverlays();drawPins();$('mapStatus').textContent=state.province?`${state.province}: exact canonical border, center, pins, longitudes, latitudes and UTC loaded.`:'Choose a province to reveal its canonical border and all pins.'}
function selectProvince(name,focus=true){state.province=name||'';$('provinceSelect').value=state.province;apply();if(state.province){showProvince(state.province);if(focus)focusProvince(state.province)}else{$('provinceDetails').innerHTML='<div class="card"><h3>Select a province</h3><p class="tiny">No borders or pins are shown until a province is selected.</p></div>'}}
function focusXY(x,y){const z=state.zoom,sc=$('mapScroll');sc.scrollTo({left:x*z-sc.clientWidth/2,top:y*z-sc.clientHeight/2,behavior:'smooth'})}
function focusProvince(name){const p=provinceByName.get(norm(name));if(p?.center)focusXY(p.center.x,p.center.y)}
function showProvince(name){const p=provinceByName.get(norm(name));if(!p)return;const ss=WORLD.settlements.filter(s=>norm(s.province)===norm(name));$('provinceDetails').innerHTML=`<div class="card"><h3>${esc(p.name)}</h3><div class="detail-grid"><div class="detail"><b>Government</b>${esc(p.government||p.governmentType)}</div><div class="detail"><b>Population</b>${fmt(p.population||p.overallPopulation)}</div><div class="detail"><b>Area</b>${fmt(p.squareMiles)} mi² / ${fmt(p.squareKilometers)} km²</div><div class="detail"><b>Center</b>${Number(p.center.latitude).toFixed(5)}°, ${Number(p.center.longitude).toFixed(5)}°</div><div class="detail"><b>UTC</b>${esc(p.center.utc||p.utc)}</div><div class="detail"><b>Settlements / Territories</b>${ss.length}</div><div class="detail"><b>Climate</b>${esc(p.climateRegime)}</div><div class="detail"><b>Named Weather</b>${esc(p.namedWeather)}</div></div><h3>Biomes</h3>${chipList(p.biomes||p.scannerBiomeTypes)}<h3>Factions</h3>${chipList(p.associatedFactions)}<h3>Locations</h3><div class="list">${ss.map(s=>`<div class="result" data-settlement="${esc(s.name)}"><strong>${esc(s.name)}</strong><div class="tiny">${esc(s.settlementType)} · ${Number(s.latitude).toFixed(5)}°, ${Number(s.longitude).toFixed(5)}° · ${esc(s.utc)}</div></div>`).join('')}</div></div>`;document.querySelectorAll('#provinceDetails [data-settlement]').forEach(el=>el.onclick=()=>focusSettlement(el.dataset.settlement))}
function field(s,label,value){return `<div class="detail"><b>${esc(label)}</b>${value??'—'}</div>`}
function showSettlement(s,anchor){state.selected=s;const distance=s.distanceFromProvinceCenter||{};const depth=s.depthReference||s.underwaterDepthBand||s.mappedOceanDepthBandAtPin||s.mappedBiomeOrDepth||'—';const html=`<button class="ghost popup-close" id="popupClose">Close</button><h3>${esc(s.name)}</h3><p class="tiny">${esc(s.settlementType)} in ${esc(s.province)}${s.isTerritory?' · detached territory':''}</p><div class="detail-grid">${field(s,'Population',fmt(s.population))}${field(s,'Area',`${fmt(s.squareMiles)} mi² / ${fmt(s.squareKilometers)} km²`)}${field(s,'Longitude',`${Number(s.longitude).toFixed(5)}°`)}${field(s,'Latitude',`${Number(s.latitude).toFixed(5)}°`)}${field(s,'Map Pixel',`${fmt(s.x)}, ${fmt(s.y)}`)}${field(s,'UTC',esc(s.utc))}${field(s,'Primary Biome',esc(s.primaryBiome||s.mappedBiomeAtPin))}${field(s,'Mapped Height / Depth',esc(depth))}${field(s,'Water / Land Class',esc(s.manualWaterLandClass))}${field(s,'Placement Match',esc(s.placementMatchQuality))}${field(s,'Danger',`${esc(s.dangerLevel||s.danger)} · score ${fmt(s.dangerScore)}`)}${field(s,'Distance from Province Center',distance.miles!=null?`${fmt(distance.miles)} mi / ${fmt(distance.kilometers)} km`:'—')}${field(s,'HTML Filename',esc(s.htmlFileName||s.htmlFile))}${field(s,'Province Government',esc(s.provinceGovernment))}</div><h3>Majority Population Races</h3>${chipList(s.majorityPopulationRaces)}<h3>Creator Gods of Majority Races</h3>${chipList(s.creatorGodsOfMajorityRaces)}<h3>All Recorded Races</h3>${chipList(s.races)}<h3>Race Categories</h3>${chipList(s.raceCategories)}<h3>Deities Worshipped</h3>${chipList(s.deitiesWorshipped||s.godsWorshipped)}<h3>Resources and Services</h3>${chipList(s.resourcesAndServicesProvided)}<h3>Transit</h3>${chipList(s.publicTransit||s.transportation)}<h3>Factions</h3>${chipList(s.associatedFactions)}<h3>Biomes</h3>${chipList(s.biomes)}<details><summary>Complete canonical record</summary><pre>${esc(JSON.stringify(s,null,2))}</pre></details>`;$('settlementDetails').innerHTML=`<div class="card">${html}</div>`;const pop=$('settlementPopup');pop.innerHTML=html;pop.style.display='block';const rect=anchor?.getBoundingClientRect(),stage=$('mapInner').getBoundingClientRect();pop.style.left=`${Math.max(10,Math.min(MAP_W-550,(rect?rect.left-stage.left:200)/state.zoom+20))}px`;pop.style.top=`${Math.max(10,Math.min(MAP_H-500,(rect?rect.top-stage.top:200)/state.zoom+20))}px`;pop.querySelector('#popupClose').onclick=()=>pop.style.display='none'}
function focusSettlement(name){const s=settlementByName.get(norm(name));if(!s)return;if(norm(state.province)!==norm(s.province))selectProvince(s.province,false);focusXY(s.x,s.y);showSettlement(s,null)}
function showNatural(n){$('settlementDetails').innerHTML=`<div class="card"><h3>${esc(n.name)}</h3><div class="detail-grid"><div class="detail"><b>Physical Kind</b>${esc(n.physical_kind)}</div><div class="detail"><b>Category</b>${esc(n.category)}</div><div class="detail"><b>Longitude / Latitude</b>${esc((n.coordinate_anchor||[]).join(', '))}</div><div class="detail"><b>Naming Basis</b>${esc(n.naming_basis?.method)}</div></div><h3>Lore Roots</h3>${chipList(n.lore_roots)}</div>`}
function renderSearch(){const q=norm($('search').value);const out=$('searchResults');if(!q){out.innerHTML='<div class="tiny">Search province, settlement, territory, race, deity, faction, resource, biome, transit, or natural system.</div>';return}const hits=[];WORLD.provinces.forEach(p=>{if(norm(JSON.stringify(p)).includes(q))hits.push({kind:'province',name:p.name,sub:`Province · ${p.climateRegime||''}`})});WORLD.settlements.forEach(s=>{if(norm(JSON.stringify(s)).includes(q))hits.push({kind:'settlement',name:s.name,sub:`${s.province} · ${s.settlementType}`})});naturalFeatures.forEach(n=>{if(norm(JSON.stringify(n)).includes(q))hits.push({kind:'natural',name:n.name,sub:`${n.physical_kind} · ${(n.coordinate_anchor||[]).join(', ')}`,data:n})});out.innerHTML=hits.slice(0,100).map((h,i)=>`<div class="result" data-i="${i}"><strong>${esc(h.name)}</strong><div class="tiny">${esc(h.sub)}</div></div>`).join('')||'<div class="tiny">No results.</div>';out.querySelectorAll('[data-i]').forEach(el=>{const h=hits[Number(el.dataset.i)];el.onclick=()=>h.kind==='province'?selectProvince(h.name):h.kind==='settlement'?focusSettlement(h.name):showNatural(h.data)})}
function updateClock(){const s=state.selected;const now=new Date();$('clockStatus').textContent=s?`${s.name} ${s.utc} · ${now.toUTCString()}`:`UTC now · ${now.toUTCString()}`}
function init(){
 $('provinceSelect').innerHTML='<option value="">Choose a province…</option>'+WORLD.provinces.map(p=>`<option>${esc(p.name)}</option>`).join('');
 $('provinceSelect').onchange=e=>selectProvince(e.target.value);
 ['showBorders','showCenters','showSettlements','showLabels','showRoutes','showGrid','showTimeZones','showNatural','mapZoom'].forEach(id=>$(id)?.addEventListener('input',apply));
 $('search').addEventListener('input',renderSearch);$('focusProvince').onclick=()=>focusProvince(state.province);$('resetMap').onclick=()=>{state.province='';$('provinceSelect').value='';$('mapZoom').value=1;apply();$('mapScroll').scrollTo({left:0,top:0,behavior:'smooth'})};$('showAll').onclick=()=>{const p=WORLD.provinces[0];selectProvince(p.name,false);$('showNatural').checked=true;apply()};$('closePopup').onclick=()=>$('settlementPopup').style.display='none';drawGrid();renderSearch();apply();updateClock();setInterval(updateClock,1000);$('validation').textContent=`${WORLD.counts.provinces} provinces · ${WORLD.counts.settlementsAndTerritories} settlements/territories · ${WORLD.counts.naturalSystems} natural systems · exact 2048×1024 canonical coordinate surface · corrected JSON and GeoJSON package loaded`;
}
document.addEventListener('DOMContentLoaded',init);
})();
