(function(){
  const BACKEND_URL = 'https://script.google.com/macros/s/AKfycbzoGmgKoNq_d-KorQsuBYYeJYQ0pAVk4a7Y3zFxdJncbU7GlMK_Dg2irgbR1zPfyiPr4g/exec';
  if (window.SuperbotWidgetLoaded) return; window.SuperbotWidgetLoaded = true;
  const container=document.createElement('div'); container.id='superbot-widget-container';
  Object.assign(container.style,{position:'fixed',right:'20px',bottom:'20px',zIndex:'999999',fontFamily:'Inter,system-ui,Segoe UI,Arial,sans-serif'});
  const panel=document.createElement('div'); Object.assign(panel.style,{width:'390px',height:'590px',maxHeight:'calc(100vh - 110px)',border:'1px solid rgba(0,255,255,.45)',borderRadius:'24px',overflow:'hidden',background:'#050713',boxShadow:'0 24px 70px rgba(0,0,0,.38),0 0 28px rgba(0,255,255,.2)',display:'none',marginBottom:'14px'});
  panel.innerHTML=`<div style="height:58px;background:#061124;color:#efffff;display:flex;align-items:center;justify-content:space-between;padding:0 16px;border-bottom:1px solid rgba(0,255,255,.25)"><b>superbot</b><span style="font-size:12px;color:#95ffbc">online</span></div><div id="sbw-log" style="height:420px;overflow:auto;padding:14px;color:#efffff;font-size:14px"></div><form id="sbw-form" style="display:flex;gap:8px;padding:12px;border-top:1px solid rgba(0,255,255,.18)"><textarea id="sbw-input" placeholder="Ask superbot..." style="flex:1;min-height:58px;resize:none;border-radius:14px;border:1px solid rgba(0,255,255,.2);background:rgba(255,255,255,.06);color:white;padding:10px"></textarea><button style="border:0;border-radius:14px;background:#00ffff;color:#001218;font-weight:900;padding:0 14px">Send</button></form>`;
  const button=document.createElement('button'); button.innerHTML='💬'; Object.assign(button.style,{width:'64px',height:'64px',borderRadius:'999px',background:'#00ffff',color:'#001218',border:'0',fontSize:'28px',boxShadow:'0 12px 38px rgba(0,255,255,.32)',cursor:'pointer',float:'right'});
  let open=false, conversationId='widget_'+Math.random().toString(36).slice(2);
  function log(role,text){const el=panel.querySelector('#sbw-log');const m=document.createElement('div');m.style.cssText='margin:9px 0;padding:10px 12px;border-radius:16px;white-space:pre-wrap;background:'+(role==='user'?'rgba(0,255,255,.16)':'rgba(255,255,255,.08)');m.textContent=(role==='user'?'You: ':'superbot: ')+text;el.appendChild(m);el.scrollTop=el.scrollHeight;}
  async function api(payload){const body=new URLSearchParams({payload:JSON.stringify(payload)});const r=await fetch(BACKEND_URL,{method:'POST',body});const t=await r.text();try{return JSON.parse(t)}catch{return{ok:false,raw:t}}}
  button.onclick=()=>{open=!open;panel.style.display=open?'block':'none';if(open&&!panel.dataset.greet){panel.dataset.greet='1';log('bot','I can scan code, answer project questions, make tasks, learn preferences, and simulate voice profiles.')}};
  panel.querySelector('#sbw-form').onsubmit=async e=>{e.preventDefault();const input=panel.querySelector('#sbw-input');const text=input.value.trim();if(!text)return;input.value='';log('user',text);const r=await api({action:'chats.send',conversationId,message:text});log('bot',r.reply||r.error||JSON.stringify(r));};
  container.appendChild(panel);container.appendChild(button);document.body.appendChild(container);
  const mq=window.matchMedia('(max-width:480px)');function mobile(e){if(e.matches){panel.style.width='calc(100vw - 30px)';panel.style.height='calc(100vh - 110px)';}else{panel.style.width='390px';panel.style.height='590px';}};mq.addEventListener?mq.addEventListener('change',mobile):mq.addListener(mobile);mobile(mq);
})();
