let openAIBaseURL = '';
let transcriptURL = '';
let AZURE_SPEAKER_LIST_API = '';
let AZURE_SPEAKER_TTS_API = '';
let OPENAI_AUDIO_TO_TEXT_API = '';
let OPENAI_SPEAKER_TTS_API = '';
let MOON_SPEAKER_TTS_API = '';
let FISH_AUDIO_SPEAKER_LIST_API = '';
let FISH_AUDIO_SPEAKER_TTS_API = '';
let FISH_AUDIO_CLONE_API = '';
let MINIMAX_SPEAKER_TTS_API = '';
let MINIMAX_SPEAKER_STATUS_API = '';
let MINIMAX_SPEAKER_DOWNLOAD_API = '';
let UPLOAD_API = '';
let API_KEY = '';
let REGION = '';

openAIBaseURL = 'https://' + process.env.NEXT_PUBLIC_PROD_API_HOST + '/v1/';
transcriptURL =
  'https://' + process.env.NEXT_PUBLIC_PROD_API_HOST + '/302/transcript?url=';
AZURE_SPEAKER_LIST_API =
  process.env.NEXT_PUBLIC_PROD_AZURE_SPEAKER_LIST_API || '';
AZURE_SPEAKER_TTS_API =
  process.env.NEXT_PUBLIC_PROD_AZURE_SPEAKER_TTS_API || '';
OPENAI_AUDIO_TO_TEXT_API =
  process.env.NEXT_PUBLIC_PROD_OPENAI_AUDIO_TO_TEXT_API || '';
OPENAI_SPEAKER_TTS_API =
  process.env.NEXT_PUBLIC_PROD_OPENAI_SPEAKER_TTS_API || '';
MOON_SPEAKER_TTS_API = process.env.NEXT_PUBLIC_PROD_MOON_SPEAKER_TTS_API || '';
FISH_AUDIO_SPEAKER_LIST_API =
  process.env.NEXT_PUBLIC_PROD_FISH_AUDIO_SPEAKER_LIST_API || '';
FISH_AUDIO_SPEAKER_TTS_API =
  process.env.NEXT_PUBLIC_PROD_FISH_AUDIO_SPEAKER_TTS_API || '';
FISH_AUDIO_CLONE_API = process.env.NEXT_PUBLIC_PROD_FISH_AUDIO_CLONE_API || '';
MINIMAX_SPEAKER_TTS_API =
  process.env.NEXT_PUBLIC_PROD_MINIMAX_SPEAKER_TTS_API || '';
MINIMAX_SPEAKER_STATUS_API =
  process.env.NEXT_PUBLIC_PROD_MINIMAX_SPEAKER_STATUS_API || '';
MINIMAX_SPEAKER_DOWNLOAD_API =
  process.env.NEXT_PUBLIC_PROD_MINIMAX_SPEAKER_DOWNLOAD_API || '';
API_KEY = process.env.NEXT_PUBLIC_API_KEY || '';
REGION = process.env.NEXT_PUBLIC_REGION || '';
UPLOAD_API = process.env.NEXT_PUBLIC_UPLOAD_API || '';
export {
  API_KEY,
  AZURE_SPEAKER_LIST_API,
  AZURE_SPEAKER_TTS_API,
  FISH_AUDIO_CLONE_API,
  FISH_AUDIO_SPEAKER_LIST_API,
  FISH_AUDIO_SPEAKER_TTS_API,
  MINIMAX_SPEAKER_DOWNLOAD_API,
  MINIMAX_SPEAKER_STATUS_API,
  MINIMAX_SPEAKER_TTS_API,
  MOON_SPEAKER_TTS_API,
  OPENAI_AUDIO_TO_TEXT_API,
  OPENAI_SPEAKER_TTS_API,
  REGION, UPLOAD_API, openAIBaseURL,
  transcriptURL
};

