import { seededRandom, clamp } from './math.js';

function seedFrom(value='worldforge'){let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function point(id,name,type,description,position,color,size,velocity,bounds,details={}){const renderAsPoint=details.renderAsPoint!==false;return{id,name,type,description,position:new Float32Array(position),color,size,velocity:velocity?new Float32Array(velocity):null,bounds,renderAsPoint,details,source:'WorldForge Immersive Systems'};}
function emptyMesh(){return{positions:new Float32Array(),colors:new Float32Array(),indices:new Uint32Array()};}
function meshBuilder(){
  const p=[],c=[],idx=[];const addVertex=(v,color)=>{p.push(...v);c.push(...color);return p.length/3-1;};
  function addBox(x,y,z,sx,sy,sz,color){const v=[[x-sx,y-sy,z-sz],[x+sx,y-sy,z-sz],[x+sx,y+sy,z-sz],[x-sx,y+sy,z-sz],[x-sx,y-sy,z+sz],[x+sx,y-sy,z+sz],[x+sx,y+sy,z+sz],[x-sx,y+sy,z+sz]].map(q=>addVertex(q,color)),f=[[0,1,2,0,2,3],[4,6,5,4,7,6],[0,4,5,0,5,1],[3,2,6,3,6,7],[1,5,6,1,6,2],[0,3,7,0,7,4]];for(const a of f)idx.push(...a.map(i=>v[i]));}
  function addPyramid(x,y,z,r,h,color,sides=7){const base=[];for(let i=0;i<sides;i++){const a=i/sides*Math.PI*2;base.push(addVertex([x+Math.cos(a)*r,y,z+Math.sin(a)*r],color));}const top=addVertex([x,y+h,z],color),center=addVertex([x,y,z],color);for(let i=0;i<sides;i++){const n=(i+1)%sides;idx.push(base[i],base[n],top,center,base[n],base[i]);}}
  function addFish(x,y,z,length,height,color,heading=0){const ch=Math.cos(heading),sh=Math.sin(heading),tx=(dx,dz)=>[x+dx*ch-dz*sh,y,z+dx*sh+dz*ch],v0=addVertex(tx(length*.52,0),color),v1=addVertex([x,y+height*.55,z],color),v2=addVertex(tx(-length*.38,height*.22),color),v3=addVertex([x,y-height*.55,z],color),v4=addVertex(tx(-length*.38,-height*.22),color),tail=addVertex(tx(-length*.72,0),color),tailUp=addVertex([tail? p[tail*3]:x,y+height*.58,tail?p[tail*3+2]:z],color),tailDn=addVertex([tail? p[tail*3]:x,y-height*.58,tail?p[tail*3+2]:z],color);idx.push(v0,v1,v2,v0,v2,v3,v0,v3,v4,v0,v4,v1,v2,v4,v3,v2,v1,v4,tail,tailUp,tailDn);}
  function addKelp(x,y,z,h,color,bend=.7){let prevL=null,prevR=null;const segments=7;for(let i=0;i<=segments;i++){const t=i/segments,yy=y+t*h,xx=x+Math.sin(t*3.4)*bend*t,zz=z+Math.cos(t*2.7)*bend*.4*t,w=.10*(1-t*.55),l=addVertex([xx-w,yy,zz],color),r=addVertex([xx+w,yy,zz],color);if(prevL!==null)idx.push(prevL,l,prevR,prevR,l,r);prevL=l;prevR=r;}}
  function addCoral(x,y,z,scale,color,rnd){addPyramid(x,y,z,.18*scale,.9*scale,color,6);const branches=3+Math.floor(rnd()*4);for(let i=0;i<branches;i++){const a=i/branches*Math.PI*2+rnd()*.4,rr=.18*scale+rnd()*.18*scale,hh=.35*scale+rnd()*.55*scale;addPyramid(x+Math.cos(a)*rr,y+.35*scale,z+Math.sin(a)*rr,.08*scale,hh,color,5);}}
  function addRibbon(x,y,z,length,width,color,heading=0){const ch=Math.cos(heading),sh=Math.sin(heading),segments=12,left=[],right=[];for(let i=0;i<=segments;i++){const t=i/segments,dx=(t-.5)*length,dz=Math.sin(t*Math.PI*2)*width*.45,yy=y+Math.sin(t*Math.PI*3)*.08,l=[x+dx*ch-(dz-width*.5)*sh,yy,z+dx*sh+(dz-width*.5)*ch],r=[x+dx*ch-(dz+width*.5)*sh,yy,z+dx*sh+(dz+width*.5)*ch];left.push(addVertex(l,color));right.push(addVertex(r,color));if(i)idx.push(left[i-1],left[i],right[i-1],right[i-1],left[i],right[i]);}}
  return{addBox,addPyramid,addFish,addKelp,addCoral,addRibbon,finish:()=>({positions:new Float32Array(p),colors:new Float32Array(c),indices:new Uint32Array(idx)})};
}

export class PatternedWeatherSystem{
  constructor(simulation){this.simulation=simulation;this.patterns=[];this.lastKey='';}
  pattern(record,date=this.simulation.date(),horizon='daily'){
    const dayOfYear=Math.floor((Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate())-Date.UTC(date.getUTCFullYear(),0,0))/86400000),week=Math.floor(dayOfYear/7),month=date.getUTCMonth(),year=date.getUTCFullYear(),latitude=Number(record?.lat)||0,biomes=record?.biomes||[],water=biomes.some(x=>/ocean|water|reef|coast|marsh|swamp/i.test(typeof x==='string'?x:x.name)),mountain=biomes.some(x=>/mountain|valley|cavern/i.test(typeof x==='string'?x:x.name)),seasonalPhase=Math.cos((dayOfYear/365.2422*Math.PI*2)+(latitude<0?Math.PI:0)),annualTemp=(water?19:23)-Math.abs(latitude)*.32+(latitude>=0?1:-1)*seasonalPhase*(water?5:13)-(mountain?9:0),dailyRnd=seededRandom(seedFrom(`${record?.id}:d:${year}:${dayOfYear}`)),weeklyRnd=seededRandom(seedFrom(`${record?.id}:w:${year}:${week}`)),monthlyRnd=seededRandom(seedFrom(`${record?.id}:m:${year}:${month}`)),monsoon=Math.max(0,Math.sin((month/12*Math.PI*2)+(record?.lon||0)/180*Math.PI)),moisture=clamp((water?.72:.38)+(monthlyRnd()-.5)*.28+monsoon*.22,0,1),pressure=1013+(weeklyRnd()-.5)*38-seasonalPhase*5,stormCycle=(Math.sin((dayOfYear+seedFrom(record?.id)%31)/9.7)+1)/2,intensity=clamp(.08+stormCycle*.42+moisture*.3+(dailyRnd()-.5)*.28,0,1),wind=4+weeklyRnd()*34+intensity*38+(mountain?10:0),precip=clamp((moisture-.35)*135+intensity*42+(dailyRnd()-.5)*18,0,100),temp=annualTemp+(dailyRnd()-.5)*7,kind=temp<-2?(precip>35?'Snow system':'Cold clear interval'):intensity>.77?'Severe storm front':intensity>.55?'Rain and thunder band':moisture>.72?'Fog and low cloud bank':wind>38?'Wind line':'Stable weather interval',duration={daily:1,weekly:7,monthly:30,annual:365}[horizon]||1;
    return{name:record?.weatherName||kind,horizon,durationDays:duration,intensity,temperatureC:temp,windSpeed:wind,precipitationChance:precip,pressureHpa:pressure,seasonalPhase,dayOfYear,week,month:month+1,year,summary:`${record?.climateBelt||'Planetary climate'} · ${kind}. ${Math.round(temp)} °C, ${Math.round(wind)} km/h winds, ${Math.round(precip)}% precipitation, ${Math.round(pressure)} hPa. Deterministic for the same world date and location.`};
  }
  worldCells(catalog){
    const groups=new Map();for(const s of catalog?.settlements||[]){if(!groups.has(s.province||'World'))groups.set(s.province||'World',[]);groups.get(s.province||'World').push(s);}const cells=[];
    if(!groups.size){
      for(let lat=-60;lat<=60;lat+=30)for(let lon=-150;lon<=150;lon+=60){const id=`global:${lat}:${lon}`,r={id,lat,lon,biomes:Math.abs(lat)<30?['Ocean','Rainforest']:Math.abs(lat)>45?['Tundra']:['Grassland'],climateBelt:Math.abs(lat)<25?'Tropical circulation':Math.abs(lat)>50?'Polar circulation':'Temperate circulation'},snap=this.pattern(r,this.simulation.date(),'weekly');cells.push({id:`pattern-weather:${id}`,name:snap.name,type:'weather system',lat,lon,elevation_m:9000+snap.intensity*5000,description:snap.summary,province:'Global circulation',intensity:snap.intensity,drift:(seedFrom(id)%2001-1000)/32000,weatherPattern:snap});}
      return cells;
    }
    for(const [province,list] of groups){const r=list[0],snap=this.pattern(r,this.simulation.date(),'weekly');cells.push({id:`pattern-weather:${province}`,name:r.weatherName||`${province} weather`,type:'weather system',lat:list.reduce((a,b)=>a+Number(b.lat||0),0)/list.length,lon:list.reduce((a,b)=>a+Number(b.lon||0),0)/list.length,elevation_m:9000+snap.intensity*5000,description:snap.summary,province,intensity:snap.intensity,drift:(seedFrom(province)%2001-1000)/28000,weatherPattern:snap});}return cells;
  }
}

export class MarineEcosystem{
  constructor(model){this.model=model;}
  build(focus,profile={},count=1450){return this.buildScene(focus,profile,count).objects;}
  buildScene(focus,profile={},count=1450){
    const rnd=seededRandom(seedFrom(`${this.model.seed}:${focus.lat}:${focus.lon}:marine-v4`)),objects=[],builder=meshBuilder(),names={reef:['coral turtle','reef ray','parrotfish school','sea horse','reef shark','anemone colony','giant clam'],shelf:['silverfin school','kelp grazer','seal','coastal dolphin','squid','sturgeon'],slope:['lantern whale','swordfish','glass shark','ribbon eel','jelly bloom'],abyss:['anglerfish','vampire squid','giant isopod','abyssal ray','siphonophore','vent crab'],trench:['hadal snailfish','amphipod swarm','trench eel','blind octopus','vent tube worm']},hasReef=(profile?.biomes||[]).some(b=>/reef/i.test(b.name||b));
    for(let i=0;i<count;i++){
      const x=(rnd()-.5)*28,z=(rnd()-.5)*28,normalizedDepth=rnd();let zone=normalizedDepth<.18?'reef':normalizedDepth<.42?'shelf':normalizedDepth<.68?'slope':normalizedDepth<.88?'abyss':'trench';if(!hasReef&&zone==='reef')zone='shelf';const y=5.0-normalizedDepth*9.0+(rnd()-.5)*.65,species=names[zone][Math.floor(rnd()*names[zone].length)],school=/school|swarm|bloom|colony/i.test(species),speed=zone==='trench'?.018:zone==='abyss'?.03:zone==='slope'?.055:.09,color=zone==='reef'?[.35+rnd()*.5,.7+rnd()*.25,.55+rnd()*.35]:zone==='trench'?[.32,.62+rnd()*.25,.86]:[.18+rnd()*.45,.5+rnd()*.4,.68+rnd()*.3];
      const o=point(`marine:${i}`,`${species[0].toUpperCase()+species.slice(1)} ${i+1}`,'Sea creature',`${species} occupying the ${zone} ecological band between the moving water column and mapped seabed.`,[x,y,z],color,school?3+rnd()*4:5+rnd()*8,[(rnd()-.5)*speed,(rnd()-.5)*speed*.18,(rnd()-.5)*speed],[14,5.2,14],{zone,trophicLevel:1+Math.floor(rnd()*5),depthBand:normalizedDepth,currentAffinity:rnd(),plateContext:normalizedDepth>.75?'oceanic plate / trench':'continental shelf to oceanic slope',renderAsPoint:false});objects.push(o);const bodyScale=school?.16+rnd()*.22:.28+rnd()*.56;builder.addFish(x,y,z,bodyScale,.08+bodyScale*.34,color,rnd()*Math.PI*2);
    }
    for(let i=0;i<170;i++){const x=(rnd()-.5)*27,z=(rnd()-.5)*27,zone=i<72?'reef':i<125?'shelf':'abyss',y=zone==='abyss'?-3.55:-3.85+rnd()*.45,color=zone==='reef'?[.78,.25+rnd()*.48,.44+rnd()*.35]:zone==='shelf'?[.08,.42+rnd()*.28,.14]:[.42,.68,.76];objects.push(point(`marine-flora:${i}`,zone==='reef'?`Coral colony ${i+1}`:zone==='shelf'?`Kelp stand ${i+1}`:`Vent ecosystem ${i+1}`,'Marine ecosystem producer',`Stationary ${zone} habitat supporting local food webs.`,[x,y,z],color,4+rnd()*7,null,null,{zone,primaryProducer:true,renderAsPoint:false}));if(zone==='reef')builder.addCoral(x,y,z,.65+rnd()*1.45,color,rnd);else if(zone==='shelf')builder.addKelp(x,y,z,1.2+rnd()*2.4,color,.35+rnd()*.9);else{builder.addBox(x,y,z,.12,.7+rnd()*1.1,.12,[.12,.18,.2]);builder.addPyramid(x,y+.5,z,.16,.8+rnd()*.7,[.55,.72,.74],6);}}
    for(let i=0;i<75;i++){const x=(rnd()-.5)*28,z=(rnd()-.5)*28,y=-4.05+rnd()*.28,scale=.25+rnd()*.8;builder.addPyramid(x,y,z,scale,.18+rnd()*.6,[.12+rnd()*.1,.18+rnd()*.1,.2+rnd()*.12],7);}
    for(let i=0;i<16;i++){const y=-3.2+rnd()*6.5;builder.addRibbon((rnd()-.5)*6,y,(rnd()-.5)*12,18+rnd()*12,.12+rnd()*.18,[.07,.42,.53],rnd()*Math.PI);}
    return{objects,mesh:builder.finish(),stats:{creatures:count,habitatObjects:245,zones:['reef','shelf','slope','abyss','trench']}};
  }
}

export class CaveExplorerSystem{constructor(caveData){this.data=caveData;}points(){const stations=this.data?.stations||[];return stations.map((s,i)=>point(`cave-station:${i}`,s.name||`Cavern chamber ${i+1}`,i===0?'Cave entrance':'Cavern chamber',`Surveyed chamber ${i+1}; width ${s.width||2.4}, height ${s.height||2}.`,[Number(s.x)||0,Number(s.z??s.y)||0,Number(s.y??s.z)||0],[.72,.55,.9],8,null,null,{stationIndex:i,width:s.width,height:s.height,connections:s.connections||[],renderAsPoint:false}));}}
export class VolcanoSystem{constructor(simulation){this.simulation=simulation;}state(feature){const d=this.simulation.date(),day=Math.floor(d.getTime()/86400000),rnd=seededRandom(seedFrom(`${feature?.id||feature?.name}:${Math.floor(day/7)}`)),cycle=7+Math.floor(rnd()*180),phase=((day+seedFrom(feature?.name)%cycle)%cycle)/cycle,activity=clamp(Math.pow(Math.sin(phase*Math.PI),8)*(0.35+rnd()*.65),0,1);return{cycleDays:cycle,phase,activity,erupting:activity>.62,plumeHeightM:activity*18000,lavaFlowKm:activity*12,summary:activity>.82?'Major eruptive pulse':activity>.62?'Active eruption':activity>.3?'Elevated unrest':'Background geothermal activity'};}}
